# Generated by Django 5.0.4 on 2024-04-22 07:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('password', models.CharField(max_length=250, validators=[django.core.validators.MaxLengthValidator(limit_value=250), django.core.validators.MinLengthValidator(limit_value=8, message='Password must be at least 8 characters')])),
                ('is_active', models.BooleanField(default=True)),
                ('confirm_password', models.CharField(max_length=250, validators=[django.core.validators.MaxLengthValidator(limit_value=250), django.core.validators.MinLengthValidator(limit_value=8, message='Password must be at least 8 characters')])),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=50)),
                ('projectDescription', models.CharField(max_length=500)),
                ('projectStartDate', models.DateField(default=django.utils.timezone.now)),
                ('projectEndDate', models.DateField(null=True)),
                ('projectStatus', models.CharField(choices=[('In progress', 'In progress'), ('Completed', 'Completed')], max_length=100)),
                ('assignToPM', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_to_pm', to='department.customuser')),
                ('projectCreator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='department.customuser')),
            ],
        ),
    ]
