# Generated by Django 5.0.4 on 2024-05-01 09:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('password', models.CharField(max_length=250, validators=[django.core.validators.MaxLengthValidator(limit_value=250), django.core.validators.MinLengthValidator(limit_value=8, message='Password must be at least 8 characters')])),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Project_Manager', 'Project_Manager'), ('Team_Leader', 'Team_Leader'), ('Employee', 'Employee')], max_length=15)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_token', to='department.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveStartDate', models.DateField(default=django.utils.timezone.now)),
                ('leaveEndDate', models.DateField(null=True)),
                ('leaveType', models.CharField(choices=[('half-day', 'half-day'), ('full-day', 'full-day')], default='full-day', max_length=100)),
                ('leaveReason', models.CharField(max_length=500)),
                ('approveLeave', models.BooleanField(default=False, null=True)),
                ('leave_days', models.IntegerField(default=0)),
                ('empName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves_requested', to='department.customuser')),
                ('notifyTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves_notified', to='department.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=50)),
                ('projectDescription', models.CharField(max_length=500)),
                ('projectStartDate', models.DateField()),
                ('projectEndDate', models.DateField(null=True)),
                ('projectStatus', models.CharField(choices=[('In progress', 'In progress'), ('Completed', 'Completed')], max_length=100, null=True)),
                ('assignToProject_Manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_to_pm', to='department.customuser')),
                ('projectCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='department.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('taskName', models.CharField(max_length=100)),
                ('taskDescription', models.CharField(max_length=500)),
                ('taskStartDate', models.DateField(null=True)),
                ('taskEndDate', models.DateField(null=True)),
                ('taskStatus', models.BooleanField(default=False, null=True)),
                ('emp_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.customuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.project')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.customuser')),
            ],
        ),
    ]
