# Generated by Django 5.0.4 on 2024-05-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='payment_method',
        ),
    ]
