# Generated by Django 5.0.4 on 2024-04-26 12:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_customtoken_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='assignToProject_Manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_to_pm', to='department.customuser'),
        ),
        migrations.AlterField(
            model_name='customtoken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 12, 12, 25, 789402)),
        ),
        migrations.CreateModel(
            name='allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectiscompleted', models.BooleanField(default=False)),
                ('total_members', models.IntegerField(default=0)),
                ('is_online', models.BooleanField(default=False)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='department.customuser')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.customuser')),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectnumber', to='department.project')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.project')),
                ('projectsatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='department.project')),
            ],
        ),
    ]
