# Generated by Django 5.0.4 on 2024-04-26 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_customuser_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 12, 21, 50, 123375)),
        ),
    ]
