# Generated by Django 5.0.4 on 2024-04-29 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_alter_customtoken_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 4, 25, 33, 470091)),
        ),
    ]
