# Generated by Django 5.0.4 on 2024-04-29 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_alter_customtoken_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Project_Manager', 'Project_Manager'), ('Team_Leader', 'Team_Leader'), ('Employee', 'Employee')], default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customtoken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 4, 53, 49, 651506)),
        ),
    ]
