# Generated by Django 5.0.4 on 2024-04-29 05:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_alter_customtoken_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 5, 59, 23, 450665)),
        ),
        migrations.CreateModel(
            name='ProjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('taskName', models.CharField(max_length=100, null=True)),
                ('taskDescription', models.CharField(max_length=500, null=True)),
                ('taskStartDate', models.DateField(null=True)),
                ('taskEndDate', models.DateField(null=True)),
                ('taskStatus', models.BooleanField(default=False, null=True)),
                ('emp_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.customuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.project')),
            ],
        ),
        migrations.DeleteModel(
            name='allocation',
        ),
    ]
