# Generated by Django 5.0.4 on 2024-04-29 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0010_remove_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 6, 55, 0, 609371)),
        ),
        migrations.AlterField(
            model_name='projectallocation',
            name='taskDescription',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectallocation',
            name='taskName',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
