# Generated by Django 5.0.4 on 2024-04-29 08:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0016_alter_customtoken_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 8, 38, 38, 560271)),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveStartDate', models.DateField()),
                ('leaveEndDate', models.DateField()),
                ('leaveType', models.CharField(choices=[('full-day', 'full-day'), ('half-day', 'half-day')], default='full-day', max_length=100)),
                ('leaveReason', models.CharField(max_length=500)),
                ('approveLeave', models.BooleanField(default=False, null=True)),
                ('leave_days', models.IntegerField(default=0)),
                ('EmployeeName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves_requested', to='department.customuser')),
                ('notifyTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves_notified', to='department.customuser')),
            ],
        ),
    ]
