# Generated by Django 5.0.4 on 2024-04-30 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0018_alter_customtoken_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 6, 12, 38, 946864)),
        ),
    ]
